//
// NerdFontGlyphMetadata.generated.swift
//
// Generated by tools/NerdFontMetadataGen — DO NOT EDIT.
// Source: Nerd Fonts 3.4.0 glyphnames.json + SymbolsNerdFont-Regular.ttf.
// Regenerate with: swift run --package-path tools/NerdFontMetadataGen
//

import Foundation

enum NerdFontGlyphMetadata {
    static let version = "3.4.0"

    enum PolicyClass: UInt8 {
        /// Default icon: preserve aspect ratio, fit and center in the cell.
        case icon
        /// Powerline-style: fill the cell exactly on both axes.
        case stretch
    }

    struct Entry {
        let lower: UInt32
        let upper: UInt32
        let policy: PolicyClass
    }

    /// Sorted, non-overlapping codepoint ranges of every glyph the pinned
    /// symbols font supplies (10386 codepoints).
    static let entries: [Entry] = [
        Entry(lower: 0x23FB, upper: 0x23FE, policy: .icon),
        Entry(lower: 0x2665, upper: 0x2665, policy: .icon),
        Entry(lower: 0x26A1, upper: 0x26A1, policy: .icon),
        Entry(lower: 0x2B58, upper: 0x2B58, policy: .icon),
        Entry(lower: 0xE000, upper: 0xE00A, policy: .icon),
        Entry(lower: 0xE0A0, upper: 0xE0A3, policy: .stretch),
        Entry(lower: 0xE0B0, upper: 0xE0C8, policy: .stretch),
        Entry(lower: 0xE0CA, upper: 0xE0CA, policy: .stretch),
        Entry(lower: 0xE0CC, upper: 0xE0D2, policy: .stretch),
        Entry(lower: 0xE0D4, upper: 0xE0D4, policy: .stretch),
        Entry(lower: 0xE0D6, upper: 0xE0D7, policy: .stretch),
        Entry(lower: 0xE200, upper: 0xE2A9, policy: .icon),
        Entry(lower: 0xE300, upper: 0xE3E3, policy: .icon),
        Entry(lower: 0xE5FA, upper: 0xE6B8, policy: .icon),
        Entry(lower: 0xE700, upper: 0xE8EF, policy: .icon),
        Entry(lower: 0xEA60, upper: 0xEA88, policy: .icon),
        Entry(lower: 0xEA8A, upper: 0xEA8C, policy: .icon),
        Entry(lower: 0xEA8F, upper: 0xEAC7, policy: .icon),
        Entry(lower: 0xEAC9, upper: 0xEAC9, policy: .icon),
        Entry(lower: 0xEACC, upper: 0xEAFA, policy: .icon),
        Entry(lower: 0xEAFC, upper: 0xEB09, policy: .icon),
        Entry(lower: 0xEB0B, upper: 0xEB4E, policy: .icon),
        Entry(lower: 0xEB50, upper: 0xEC1E, policy: .icon),
        Entry(lower: 0xED00, upper: 0xEFCE, policy: .icon),
        Entry(lower: 0xF000, upper: 0xF381, policy: .icon),
        Entry(lower: 0xF400, upper: 0xF533, policy: .icon),
        Entry(lower: 0xF0001, upper: 0xF0387, policy: .icon),
        Entry(lower: 0xF0389, upper: 0xF043C, policy: .icon),
        Entry(lower: 0xF043E, upper: 0xF0508, policy: .icon),
        Entry(lower: 0xF050A, upper: 0xF05FB, policy: .icon),
        Entry(lower: 0xF05FD, upper: 0xF0764, policy: .icon),
        Entry(lower: 0xF0767, upper: 0xF08CF, policy: .icon),
        Entry(lower: 0xF08D1, upper: 0xF0B38, policy: .icon),
        Entry(lower: 0xF0B3A, upper: 0xF0C9D, policy: .icon),
        Entry(lower: 0xF0CA0, upper: 0xF1087, policy: .icon),
        Entry(lower: 0xF1089, upper: 0xF108B, policy: .icon),
        Entry(lower: 0xF108D, upper: 0xF1090, policy: .icon),
        Entry(lower: 0xF1092, upper: 0xF13A5, policy: .icon),
        Entry(lower: 0xF13A7, upper: 0xF189F, policy: .icon),
        Entry(lower: 0xF18A1, upper: 0xF18EF, policy: .icon),
        Entry(lower: 0xF18F1, upper: 0xF1AF0, policy: .icon),
    ]

    /// The placement class for `scalar`, or nil when the scalar is not a
    /// Nerd Font candidate. Exact-set membership: unrelated private-use
    /// scalars stay untouched.
    static func policyClass (for scalar: UInt32) -> PolicyClass? {
        var low = 0
        var high = entries.count - 1
        while low <= high {
            let mid = (low + high) / 2
            let entry = entries[mid]
            if scalar < entry.lower {
                high = mid - 1
            } else if scalar > entry.upper {
                low = mid + 1
            } else {
                return entry.policy
            }
        }
        return nil
    }
}
